version: '3.1'

services:
  web:  
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    container_name: finance-control-web
    depends_on:
      - mongodb    
    ports:
      - "8500:8500"
    networks:
      - fc-network
    environment:
      - PORT
      - MONGO_ATLAS_URI
      - GOOGLE_CLIENT_ID 
      - GOOGLE_CLIENT_SECRET
      - GOOGLE_CALLBACK_URL
      - USERS_API_ADMIN_EMAIL

  mongodb:
    image: mongo:8.0.9
    container_name: finance-control-db
    networks:
      - fc-network
    volumes:
      - /opt/finance-control/data/fc-db/:/config:/data/fc-db
      - /opt/finance-control/backup_data:/backup_data/

networks:
  fc-network:
    driver: bridge

volumes:
  mongo_data:
  backup_data:
